name: .NET Build (Windows)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: '1'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore NuGet packages
        run: |
          dotnet restore "EasiPluginSample.sln"

      - name: Build solution (Release)
        run: |
          dotnet build "EasiPluginSample.sln" -c Release --no-restore

      - name: Publish project outputs
        run: |
          dotnet publish "src/EasiPluginSample/EasiPluginSample.csproj" -c Release -o "artifacts/EasiPluginSample" --no-build

      - name: List artifacts folder
        run: |
          dir artifacts

      - name: Archive build outputs
        run: |
          powershell -Command "Compress-Archive -Path artifacts/* -DestinationPath build_artifact.zip -Force"

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: EasiPluginSample-build
          path: build_artifact.zip
